require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.5
  Exclude:
    - db/**/*
    - bin/**/*
    - vendor/**/*
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
