require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - db/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*