language: ruby
cache:
  bundler: true
  yarn: true
addons:
  postgresql: '9.6'
before_install:
  - gem update bundler
before_script:
  - yarn
  - bundle exec rake db:create db:schema:load
script:
  - bundle exec rspec
